# Generated by Django 3.2.9 on 2021-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='modifyDate',
            field=models.DateTimeField(null=True),
        ),
    ]
