# Generated by Django 3.2.9 on 2021-11-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesb', '0003_auto_20211120_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
