# Generated by Django 3.2.9 on 2021-12-19 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notesb', '0005_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagColors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tagID', models.UUIDField()),
                ('colorID', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=128)),
            ],
        ),
    ]
